# 配置 env 变量环境信息后，将会用指定环境的配置项覆盖默认值
# 主要价值就是 方便调试
env: uat

# pytest 命令行参数，该 default 必须存在
default:
  host:
  port:
  username:
  password:
  branch: "master"

  # 邮件配置
  email_sender: ""
  email_receiver: ""
  from_name: ""
  subject: ""
  email_password: ""
  smtp_server: ""
  ssl_port: ""

# 下面两个配置 就是 env 使用的特定配置
uat:
  host: "http://www.baidu.com"
  port: "80"
  username: "123"
  password: "abc"

dev:
  host: "http://www.sina.com"
  port: "80"
  username: "123"
  password: "abc"

