# 配置 env 变量环境信息后，将会用指定环境的配置项覆盖默认值
# 主要价值就是 方便调试
env: httpbin

# pytest 命令行参数，该 default 必须存在
default:
  host:
  port:
  username:
  password:
  branch:

  # 邮件配置
  email_sender: ""  # 发件人邮箱
  email_receiver: "" # 收件人又想
  from_name: "测试"
  subject: "测试报告"
  email_password: "" # 发件人登陆密码
  smtp_server: "smtp.exmail.qq.com"
  ssl_port: "465"

# 下面两个配置 就是 env 使用的特定配置
httpbin:
  host: "http://httpbin.org"
  port: "80"
  username: "123"
  password: "abc"
